### ISSUE TITLE
If a standard matches several keywords on the same line, prompt it only once

### ISSUE THREAD

**Issue by AleBlondin** [theodo/standard-jit#3]
On the example below, query is matched 3 times, so we see 3 prompts "a technical standard may be of interest to you". It should be displayed only once.

![image](https://user-images.githubusercontent.com/25102531/153391256-22b0b72b-2229-47b6-88bf-abc58dfb8947.png)

**Comment by AleBlondin** [comment]
@NicolasJudalet :wink:

**Comment by clementmarcilhacy** [comment]
@AleBlondin we tried to reproduce the issue with @Sc0ra, it looks like it is fixed isn't it?
